version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: jokidb
      POSTGRES_USER: jokiuser
      POSTGRES_PASSWORD: jokiuser
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  pgdata:
